services:
  - docker

before_install:
  - docker build -t andriidudar11/react-test -f ./client/Dockerfile.dev ./client/

script: 
  - docker run -e CI=TRUE andriidudar11/react-test npm run test


after_success:
  - docker build -t andriidudar11/multi-client ./client
  - docker build -t andriidudar11/multi-nginx ./nginx
  - docker build -t andriidudar11/multi-server ./server
  - docker build -t andriidudar11/multi-worker ./worker

