services:
  - docker

before_install:
  - docker build -t andriidudar11/react-test -f ./client/Dockerfile.dev ./client/

script: 
  - docker run -e CI=TRUE andriidudar11/react-test npm run test


after_success:
  - docker build -t andriidudar11/multi-client ./client
  - docker build -t andriidudar11/multi-nginx ./nginx
  - docker build -t andriidudar11/multi-server ./server
  - docker build -t andriidudar11/multi-worker ./worker

# Log in to the docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push andriidudar11/multi-client
  - docker push andriidudar11/multi-nginx
  - docker push andriidudar11/multi-server
  - docker push andriidudar11/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-761677003252'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY